apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: medsim-beta
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/PROJECT_ID/simmit-images/medsim-beta:latest
          ports:
            - containerPort: 8080
