steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'gcloud',
        'run',
        'deploy',
        '${_SERVICE}',
        '--image',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$SHORT_SHA',
        '--region',
        '${_REGION}',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--set-secrets',
        'VITE_GEMINI_API_KEY=${_SECRET_GEMINI_API_KEY}:latest,VITE_SUPABASE_URL=${_SECRET_SUPABASE_URL}:latest,VITE_SUPABASE_ANON_KEY=${_SECRET_SUPABASE_ANON_KEY}:latest,VITE_SUPABASE_QUESTIONS_URL=${_SECRET_SUPABASE_QUESTIONS_URL}:latest,VITE_SUPABASE_QUESTIONS_ANON_KEY=${_SECRET_SUPABASE_QUESTIONS_ANON_KEY}:latest,VITE_SUPABASE_QUESTIONS_TABLE=${_SECRET_SUPABASE_QUESTIONS_TABLE}:latest'
      ]

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$SHORT_SHA'

substitutions:
  _SERVICE: 'medsim-beta'
  _REGION: 'us-central1'
  _AR_REPO: 'simmit-images'
  _SECRET_GEMINI_API_KEY: 'simmit-gemini-api-key'
  _SECRET_SUPABASE_URL: 'simmit-supabase-url'
  _SECRET_SUPABASE_ANON_KEY: 'simmit-supabase-anon-key'
  _SECRET_SUPABASE_QUESTIONS_URL: 'simmit-supabase-questions-url'
  _SECRET_SUPABASE_QUESTIONS_ANON_KEY: 'simmit-supabase-questions-anon-key'
  _SECRET_SUPABASE_QUESTIONS_TABLE: 'simmit-supabase-questions-table'

options:
  logging: CLOUD_LOGGING_ONLY